import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import MarketDataHeader from "./components/MarketDataHeader";
import { Providers } from "./providers";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body className={`${spaceGrotesk.className} dark:bg-[#13121A]`}>
        <Providers>
          <header>
            <MarketDataHeader />
            <Navbar />
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
